<?php
/**
 * This file contains hook implementations for the Acumulus addon.
 *
 * This file will be detected and loaded by WHMCS on every page load,
 * {@see https://developers.whmcs.com/hooks/module-hooks/}
 */

declare(strict_types=1);

if (!defined('WHMCS')) {
    die('This file cannot be accessed directly');
}

use Siel\Whmcs\Acumulus\Hooks;

/**
 * Initialises the autoloader and returns an {@see \Siel\Whmcs\Acumulus\Acumulus} instance.
 */
function getAcumulusHooks(): ?Hooks
{
    require_once __DIR__ . '/vendor/autoload.php';
    return new Hooks();
}

/**
 * Hook 'InvoiceCreated'.
 */
function acumulus_hook_invoiceCreated(array $vars): void
{
    acumulus_invoiceCreated($vars, 'InvoiceCreated');
}

/**
 * Hook 'InvoiceCreationPreEmail'.
 */
function acumulus_hook_invoiceCreationPreEmail(array $vars): void
{
    acumulus_invoiceCreated($vars, 'InvoiceCreationPreEmail');
}

/**
 * This hook is run when:
 * - A new invoice has been generated following sending the Invoice Created
 *   email (hook 'InvoiceCreated') .
 * - A new invoice has been generated by the cron, order process, API, when
 *   converting a quote to an invoice, or when published a draft invoice with
 *   email. This is run before the invoice is sent to the client (hook
 *   'InvoiceCreationPreEmail').
 *
 * @param array $vars
 * @param string $hook
 */
function acumulus_invoiceCreated(array $vars, string $hook): void
{
    getAcumulusHooks()->invoiceCreated($vars, $hook);
}

/**
 * Hook 'invoicePaid'.
 *
 * This hook is run when:
 * - An invoice is paid prior to any email or automation tasks associated with
 *   the payment action having been run.
 *
 * @param array $vars
 */
function acumulus_hook_invoicePaid(array $vars): void
{
    getAcumulusHooks()->invoicePaid($vars);
}

/**
 * Hook 'invoiceChangeGateway'.
 *
 * This hook is run when:
 * - Changing the gateway on an invoice.
 *
 * @param array $vars
 */
function acumulus_hook_invoiceChangeGateway(array $vars): void
{
    getAcumulusHooks()->invoiceChangeGateway($vars);
}

/**
 * Hook 'invoiceCancelled'.
 *
 * This hook is run when:
 * - An invoice is cancelled. This function reacts by creating a credit invoice.
 *
 * @param array $vars
 */
function acumulus_hook_invoiceCancelled(array $vars): void
{
    getAcumulusHooks()->invoiceCancelled($vars);
}

add_hook('InvoiceCreated', 500, 'acumulus_hook_invoiceCreated');
add_hook('InvoiceCreationPreEmail', 500, 'acumulus_hook_invoiceCreationPreEmail');
add_hook('InvoicePaid', 1, 'acumulus_hook_invoicePaid');
add_hook('InvoiceChangeGateway', 1, 'acumulus_hook_invoiceChangeGateway');
add_hook('InvoiceCancelled', 1, 'acumulus_hook_invoiceCancelled');
