<?php
/**
 * Addon Module acumulus_connect
 *
 * This connect module allows you to send invoices and contacts to Acumulus�.
 *  *
 * @package    acumulus_connect
 * @author     Remline ict-diensten <support@remline.nl>
 * @copyright  GPLv3  Remline ict-diensten
 * @version    3.2 April ,2021
 * @link       https://www.remline.nl
 */

if (!defined("WHMCS"))
    die("This file cannot be accessed directly");

//use Database Namespace
use Illuminate\Database\Capsule\Manager as Capsule;

include_once('acumulus_connect_functions.php');


function acumulus_connect_triggerInvoiceCreationPreEmailHook($vars) {
     // This hook is run when a new invoice has been generated by the cron, order process, when converting a quote to an invoice,
     // or when published a draft invoice with email. This is run before the invoice is sent to the client
     $CONFIG = acumulus_connect_getConfig();
     if ($CONFIG['acumulus_hook_invoice_create_enabled'] == 'on' ) {
         $invoiceid = $vars['invoiceid'];
         //$invoiceid = 1525;
         //check if invoiceid and invoicetoken are already stored and if so skip sending the invoice.
         if (!Capsule::table('mod_acumulus_connect')->where('id', $invoiceid)->exists() ) {
             // no token exists, so lets send the invoice;
            acumulus_connect_sendInvoice($CONFIG,$invoiceid, false);
         }else{
             logActivity("acumulus_connect - Skipped sending Invoice ID: ". $invoiceid ." by hook 'triggerInvoiceCreationPreEmailHook' because it was already send.");
         }
     }
}




function acumulus_connect_triggerInvoicePaidHook($vars) {
    $CONFIG = acumulus_connect_getConfig();
    if ($CONFIG['acumulus_hook_invoice_paid_enabled'] == 'on' ) {
       $invoiceid = $vars['invoiceid'];
      acumulus_connect_updateInvoice($CONFIG,$invoiceid);
    }
}

function acumulus_connect_triggerInvoiceChangeGatewayHook($vars) {
    $CONFIG = acumulus_connect_getConfig();
    $invoiceid      = $vars['invoiceid'];
    $paymentmethod  = $vars['paymentmethod'];
    acumulus_connect_updateInvoicePaymentMethode($CONFIG,$invoiceid,$paymentmethod);
}

function acumulus_connect_triggerInvoiceCanceledHook($vars) {
    $CONFIG = acumulus_connect_getConfig();
    if ($CONFIG['acumulus_hook_invoice_canceled_enabled'] == 'on' ) {
        $invoiceid      = $vars['invoiceid'];
        acumulus_connect_InvoiceCanceled($CONFIG,$invoiceid); 
    }  
}


add_hook('InvoiceCreated', 500, "acumulus_connect_triggerInvoiceCreationPreEmailHook");
// This hook is run when a new invoice has been generated following sending the Invoice Created email.

add_hook("InvoiceCreationPreEmail",500,"acumulus_connect_triggerInvoiceCreationPreEmailHook");
//This hook is run when a new invoice has been generated by the cron, order process, API, when converting a quote to an invoice, or when published a draft invoice with email. This is run before the invoice is sent to the client.

add_hook("InvoicePaid",1,"acumulus_connect_triggerInvoicePaidHook");
// Executes when an invoice is Paid prior to any email or automation tasks associated with the payment action having been run.

add_hook('InvoiceChangeGateway', 1, "acumulus_connect_triggerInvoiceChangeGatewayHook");
// Executes when changing the gateway on an invoice.

add_hook('InvoiceCancelled', 1, "acumulus_connect_triggerInvoiceCanceledHook");
