<?php

declare(strict_types=1);

namespace Siel\Whmcs\Acumulus;

use WHMCS\Database\Capsule;

use Throwable;

/**
 * Hooks contains methods to react to hooks triggered by WHMCS.
 */
class Hooks
{
    /**
     * Initialises the autoloader and returns an {@see \Siel\Whmcs\Acumulus\Acumulus} instance.
     */
    private function getAcumulus(): Acumulus
    {
        return Acumulus::getInstance();
    }

    /**
     * This hook is run when:
     * - A new invoice has been generated following sending the Invoice Created
     *   email (hook 'InvoiceCreated') .
     * - A new invoice has been generated by the cron, order process, API, when
     *   converting a quote to an invoice, or when published a draft invoice with
     *   email. This is run before the invoice is sent to the client (hook
     *   'InvoiceCreationPreEmail').
     *
     * @param array $vars
     * @param string $hook
     */
    public function invoiceCreated(array $vars, string $hook): void
    {
        logActivity(__FUNCTION__ . "('$hook'): start");
        try {
            $invoiceId = $vars['invoiceid'];
            $config = $this->getAcumulus()->get_config();
            if ($config['acumulus_hook_invoice_create_enabled'] === 'on') {
                // Check if invoice id and invoice token are already stored and, if so,
                // skip sending the invoice.
                if (!Capsule::table('mod_acumulus_connect')->where('id', $invoiceId)->exists()) {
                    // No token exists, send the invoice.
                    logActivity(__FUNCTION__ . "($invoiceId, '$hook'): sending");
                    $this->getAcumulus()->sendInvoice($config, $invoiceId);
                } else {
                    logActivity(__FUNCTION__ . "($invoiceId, '$hook'): not sending, already sent");
                }
            } else {
                logActivity(__FUNCTION__ . "($invoiceId, '$hook'): not sending, hook disabled");
            }
        } catch (Throwable $e) {
            $this->getAcumulus()->logException($e);
        }
    }

    /**
     * Hook 'invoicePaid'.
     * This hook is run when:
     * - An invoice is paid prior to any email or automation tasks associated with
     *   the payment action having been run.
     *
     * @param array $vars
     */
    public function invoicePaid(array $vars): void
    {
        logActivity(__FUNCTION__ . ': start');
        try {
            $invoiceId = $vars['invoiceid'];
            $config = $this->getAcumulus()->get_config();
            if ($config['acumulus_hook_invoice_paid_enabled'] === 'on') {
                logActivity(__FUNCTION__ . "($invoiceId): updating");
                $this->getAcumulus()->updateInvoice($config, $invoiceId);
            } else {
                logActivity(__FUNCTION__ . "($invoiceId): not updating, hook disabled");
            }
        } catch (Throwable $e) {
            $this->getAcumulus()->logException($e);
        }
    }

    /**
     * Hook 'invoiceChangeGateway'.
     * This hook is run when:
     * - Changing the gateway on an invoice.
     *
     * @param array $vars
     */
    public function invoiceChangeGateway(array $vars): void
    {
        logActivity(__FUNCTION__ . ': start');
        try {
            $config = $this->getAcumulus()->get_config();
            $invoiceId = $vars['invoiceid'];
            $paymentMethod = $vars['paymentmethod'];
            logActivity(__FUNCTION__ . "($invoiceId): changing payment method to $paymentMethod");
            $this->getAcumulus()->updateInvoicePaymentMethod($config, $invoiceId, $paymentMethod);
        } catch (Throwable $e) {
            $this->getAcumulus()->logException($e);
        }
    }

    /**
     * Hook 'invoiceCancelled'.
     * This hook is run when:
     * - An invoice is cancelled. This function reacts by creating a credit invoice.
     *
     * @param array $vars
     */
    public function invoiceCancelled(array $vars): void
    {
        logActivity(__FUNCTION__ . ': start');
        try {
            $invoiceId = $vars['invoiceid'];
            $config = $this->getAcumulus()->get_config();
            if ($config['acumulus_hook_invoice_canceled_enabled'] === 'on') {
                logActivity(__FUNCTION__ . "($invoiceId): creating credit invoice");
                $this->getAcumulus()->invoiceCancelled($config, $invoiceId);
            } else {
                logActivity(__FUNCTION__ . "($invoiceId): not creating credit invoice, hook disabled");
            }
        } catch (Throwable $e) {
            $this->getAcumulus()->logException($e);
        }
    }
}
