<?php

declare(strict_types=1);

namespace Siel\Whmcs\Acumulus;

use Siel\Acumulus\Api;
use Siel\Acumulus\Fld;
use Siel\Acumulus\Invoice\Source;
use Siel\Acumulus\Meta;
use Throwable;

/**
 * Hooks contains methods to react to hooks triggered by WHMCS.
 *
 * The public methods in this class get called by the hook functions in hook.php.
 */
class Hooks
{
    protected AcumulusHelper $helper;

    public function __construct()
    {
        $this->helper = new AcumulusHelper();
    }

    /**
     * This hook is run when:
     * - A new invoice has been generated following sending the Invoice Created
     *   email (hook 'InvoiceCreated') .
     * - A new invoice has been generated by the cron, order process, API, when
     *   converting a quote to an invoice, or when published a draft invoice with
     *   email. This is run before the invoice is sent to the client (hook
     *   'InvoiceCreationPreEmail').
     */
    public function invoiceCreated(array $vars, string $hook): void
    {
        $this->helper->logActivity('%s(%s): start', __FUNCTION__, $hook);
        try {
            $source = $this->helper->getAcumulusContainer()->createSource(Source::Invoice, $vars['invoiceid']);
            $this->helper->getAcumulusContainer()->getInvoiceManager()->invoiceCreate($source);
        } catch (Throwable $e) {
            $this->helper->logException($e);
        }
    }

    /**
     * Hook 'invoicePaid'.
     * This hook is run when:
     * - An invoice is paid prior to any email or automation tasks associated with
     *   the payment action having been run.
     *
     * See: https://developers.whmcs.com/hooks-reference/invoices-and-quotes/#invoicepaid.
     */
    public function invoicePaid(array $vars): void
    {
        $this->helper->logActivity('%s: start', __FUNCTION__);
        try {
            $source = $this->helper->getAcumulusContainer()->createSource(Source::Invoice, $vars['invoiceid']);
            // @todo: change of payment status should change template (if different per payment status)
            $this->helper->getAcumulusContainer()->getInvoiceManager()->sourceChange($source, [Fld::PaymentStatus => Api::PaymentStatus_Paid]);
        } catch (Throwable $e) {
            $this->helper->logException($e);
        }
    }

    /**
     * Hook 'invoiceChangeGateway'.
     * This hook is run when:
     * - Changing the gateway on an invoice.
     *
     * See: https://developers.whmcs.com/hooks-reference/invoices-and-quotes/#invoicechangegateway.
     */
    public function invoiceChangeGateway(array $vars): void
    {
        $this->helper->logActivity('%s: start', __FUNCTION__);
        try {
            $source = $this->helper->getAcumulusContainer()->createSource(Source::Invoice, $vars['invoiceid']);
            // @todo: change of payment method can change cost center and account number.
            $this->helper->getAcumulusContainer()->getInvoiceManager()->sourceChange($source, [Meta::PaymentMethod => $vars['paymentmethod']]);
        } catch (Throwable $e) {
            $this->helper->logException($e);
        }
    }

    /**
     * Hook 'invoiceCancelled'.
     * This hook is run when:
     * - An invoice is cancelled. This function reacts by creating a credit invoice.
     */
    public function invoiceCancelled(array $vars): void
    {
        $this->helper->logActivity('%s: start', __FUNCTION__);
        try {
            // @todo: add support for credit notes: is a separate invoice created? What is its number?
            $this->sourceStatusChange(Source::CreditNote, $vars['invoiceid']);
        } catch (Throwable $e) {
            $this->helper->logException($e);
        }
    }

    /**
     * @param string $invoiceSourceType
     *   The type of the invoice source to create.
     * @param object|int|array $invoiceSourceOrId
     *   The invoice source itself or its id to create a {@see Source} instance for.
     *
     * @throws \Throwable
     */
    private function sourceStatusChange(string $invoiceSourceType, object|int|array $invoiceSourceOrId): void
    {
        try {
            $source = $this->helper->getAcumulusContainer()->createSource($invoiceSourceType, $invoiceSourceOrId);
            $this->helper->getAcumulusContainer()->getInvoiceManager()->sourceStatusChange($source);
        } catch (Throwable $e) {
            try {
                $crashReporter = $this->helper->getAcumulusContainer()->getCrashReporter();
                // We do not know if we are on the admin side, so we should not
                // try to display the message returned by logAndMail().
                $crashReporter->logAndMail($e);
            } catch (Throwable) {
                // We don't know if we have informed the user per mail or
                // screen, so assume we didn't, and rethrow the original exception.
                throw $e;
            }
        }
    }

}
